### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by isabelcachola** [nipunsadvilkar/pySBD#27]
I get this error for some texts. 

Here is an example of where it fails:
```
>>> import pysbd
>>> text = "This new form of generalized PDF in (9) is generic and suitable for all the fading models presented in Table I withbranches MRC reception. In section III, (9) will be used in the derivations of the unified ABER and ACC expression."
>>> segmenter = pysbd.Segmenter(language="en", clean=False)
>>> sents = segmenter.segment(text)
```

**Comment by danielkingai2** [comment]
Full trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/segmenter.py", line 21, in segment
    segments = processor.process()
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/processor.py", line 30, in process
    self.text = li.add_line_break()
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/lists_item_replacer.py", line 62, in add_line_break
    self.format_numbered_list_with_parens()
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/lists_item_replacer.py", line 72, in format_numbered_list_with_parens
    self.replace_parens_in_numbered_list()
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/lists_item_replacer.py", line 152, in replace_parens_in_numbered_list
    self.NUMBERED_LIST_PARENS_REGEX, self.NUMBERED_LIST_PARENS_REGEX, '☝')
  File "/home/daniel/miniconda3/envs/spacy22test/lib/python3.6/site-packages/pysbd-0.1.1-py3.6.egg/pysbd/lists_item_replacer.py", line 125, in scan_lists
    ((item == 9) and (list_array[ind + 1] == 0))):
IndexError: list index out of range
```
