### ISSUE TITLE
crashing on input

### ISSUE THREAD

**Issue by danielkingai2** [nipunsadvilkar/pySBD#31]
pysbd crashes on this input

```
>>> segmenter.segment("Proof. First let v ∈ V be incident to at least three leaves and suppose there is a minimum power dominating set S of G that does not contain v. If S excludes two or more of the leaves of G incident to v, then those leaves cannot be dominated or forced at any step. Thus, S excludes at most one leaf incident to v, which means S contains at least two leaves ℓ 1 and ℓ 2 incident to v. Then, (S\{ℓ 1 , ℓ 2 }) ∪ {v} is a smaller power dominating set than S, which is a contradiction. Now consider the case in which v ∈ V is incident to exactly two leaves, ℓ 1 and ℓ 2 , and suppose there is a minimum power dominating set S of G such that {v, ℓ 1 , ℓ 2 } ∩ S = ∅. Then neither ℓ 1 nor ℓ 2 can be dominated or forced at any step, contradicting the assumption that S is a power dominating set. If S is a power dominating set that contains ℓ 1 or ℓ 2 , say ℓ 1 , then (S\{ℓ 1 }) ∪ {v} is also a power dominating set and has the same cardinality. Applying this to every vertex incident to exactly two leaves produces the minimum power dominating set required by (3). Definition 3.4. Given a graph G = (V, E) and a set X ⊆ V , define ℓ r (G, X) as the graph obtained by attaching r leaves to each vertex in X. If X = {v 1 , . . . , v k }, we denote the r leaves attached to vertex v i as ℓ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/miniconda3/envs/scispacy_retrain/lib/python3.6/site-packages/pysbd/segmenter.py", line 21, in segment
    segments = processor.process()
  File "/home/daniel/miniconda3/envs/scispacy_retrain/lib/python3.6/site-packages/pysbd/processor.py", line 31, in process
    self.text = AbbreviationReplacer(self.text).replace()
  File "/home/daniel/miniconda3/envs/scispacy_retrain/lib/python3.6/site-packages/pysbd/abbreviation_replacer.py", line 46, in replace
    self.text = self.search_for_abbreviations_in_string()
  File "/home/daniel/miniconda3/envs/scispacy_retrain/lib/python3.6/site-packages/pysbd/abbreviation_replacer.py", line 75, in search_for_abbreviations_in_string
    self.text = self.scan_for_replacements(self.text, match, ind, char_array)
  File "/home/daniel/miniconda3/envs/scispacy_retrain/lib/python3.6/site-packages/pysbd/abbreviation_replacer.py", line 79, in scan_for_replacements
    char = char_array[ind] if char_array else ''
IndexError: list index out of range
>>> 
```

**Comment by danielkingai2** [comment]
and sorry for the multiple issues, we would love to fully integrate pysbd into scispacy if we can iron out the issues!

**Comment by nipunsadvilkar** [comment]
@danielkingai2 : No issues! (pun-intended)😝. On bright side, it's actually making pysbd more robust and less prone to edge-cases/bugs which I hadn't accounted for in tests. Thanks for that 👍
